http:
  middlewares:
    redirect:
      redirectScheme:
        scheme: https

  routers:
    proxy:
      rule: "Host(`proxy.yourdomain.com`)"
      entryPoints:
        - "web"
      service: "api@internal"
      middlewares:
        - "redirect@file"

  services:
    proxy:
      loadBalancer:
        servers:
          - url: "http://localhost:8080"
